### ISSUE TITLE
Do not pass special variables to subroutines directly

### ISSUE THREAD

**Issue by KES777** [tobyink/p5-exporter-tiny#7]
Why:
```perl
#!/usr/bin/env perl

sub test {
	'asdf' =~ m/.*/; # This destroys received arguments
	print ">>@_<<\n";

}

my $z =  'abcd';
$z =~ m/(ab)(cd)/;
test( $1, $2 );                # >> <<
test( my $x=$1, my $y=$2 );    # >>ab cd<<
```

How regular expression could be executed when sub is called? This could occur under debugger. For example some module define `sub sub` and used regex inside that sub

**Comment by tobyink** [comment]
I'm not sure why you submitted this as an issue for Exporter::Tiny as it seems unrelated.

But it is because `@_` acts as an alias for the arguments passed to the function, not a copy. By doing `m/.*/`, you destroy `$1` and `$2`, and `@_` was only ever an alias of them, not a copy of them, so the values in it get destroyed too.

**Comment by KES777** [comment]
@tobyink 
$1 is destroyed.

https://github.com/tobyink/p5-exporter-tiny/blob/master/lib/Exporter/Tiny.pm#L26 (please also fix other places)

Would be better if you pass `"$1"` instead `$1`

**Comment by KES777** [comment]
I submitted because Exporter::Tiny uses $1 as parameter.
